"""MIDAS Gen / Civil NX adapter package (V2.1 §22).

``adapter.py`` holds the real adapter plus every module-level guard, because the
guards are pure functions that the mock adapter and the test suite reuse.
"""

from app.adapters.midas_gen.adapter import (
    BACKFILL_FIELDS,
    CAPABILITIES,
    DOCUMENTED_OUTER_KEY_MEANS,
    HIGH_RISK_ENDPOINTS,
    MANDATORY_WRITE_FIELDS,
    NEW_FILE_GET_PUT_ONLY,
    PROTECTED_PATH_PREFIXES,
    WRAPPER_ARGUMENT,
    WRAPPER_ASSIGN,
    MidasCivilAdapter,
    MidasGenAdapter,
    MidasNxAdapter,
    apply_write_contract,
    build_assign,
    build_assign_body,
    coerce_assign_records,
    find_table_shape,
    guard_local_path,
    is_hyper_s_only,
    load_case_suffix_warnings,
    normalise_endpoint,
    outer_key_means,
    require_table_components,
    resource_of,
    unwrap_response,
    validate_assign_outer_key,
    wrap_payload,
)

__all__ = [
    "MidasNxAdapter",
    "MidasGenAdapter",
    "MidasCivilAdapter",
    "WRAPPER_ASSIGN",
    "WRAPPER_ARGUMENT",
    "DOCUMENTED_OUTER_KEY_MEANS",
    "BACKFILL_FIELDS",
    "MANDATORY_WRITE_FIELDS",
    "NEW_FILE_GET_PUT_ONLY",
    "HIGH_RISK_ENDPOINTS",
    "PROTECTED_PATH_PREFIXES",
    "CAPABILITIES",
    "normalise_endpoint",
    "resource_of",
    "outer_key_means",
    "validate_assign_outer_key",
    "build_assign",
    "build_assign_body",
    "coerce_assign_records",
    "wrap_payload",
    "unwrap_response",
    "find_table_shape",
    "require_table_components",
    "load_case_suffix_warnings",
    "apply_write_contract",
    "guard_local_path",
    "is_hyper_s_only",
]
