#!/usr/bin/env python3
"""
Merge the per-part endpoint extracts in docs/api-registry/ into:
  1. midas_api_registry.json  — single machine-readable registry
  2. ENDPOINT_INDEX.md        — human-readable endpoint table
  3. a console report

Usage:  python merge_registry.py
No third-party dependencies.
"""

from __future__ import annotations

import collections
import glob
import json
import os
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
PART_GLOB = os.path.join(BASE, "part-*.json")
OUT_JSON = os.path.join(BASE, "midas_api_registry.json")
OUT_MD = os.path.join(BASE, "ENDPOINT_INDEX.md")

VALID_CATEGORIES = {"doc", "db", "ope", "view", "post", "design"}
VALID_OPERATIONS = {"create", "read", "update", "delete", "execute"}


def load_parts() -> tuple[list[dict], list[dict], list[str]]:
    """Return ``(endpoint_parts, plugin_catalogs, load_errors)``.

    ``part-16.json`` is a *plugin catalogue* — MIDAS GUI plug-ins rather than
    REST endpoints — so it is separated out instead of failing as a malformed
    part. Anything else missing ``chapters`` is a genuine error.
    """
    parts: list[dict] = []
    catalogs: list[dict] = []
    errors: list[str] = []
    for path in sorted(glob.glob(PART_GLOB)):
        name = os.path.basename(path)
        try:
            with open(path, "r", encoding="utf-8") as fh:
                data = json.load(fh)
        except json.JSONDecodeError as exc:
            errors.append(f"{name}: invalid JSON -> {exc}")
            continue
        if not isinstance(data, dict):
            errors.append(f"{name}: top level is not an object")
            continue
        if data.get("kind") == "plugin_catalog":
            catalogs.append(data)
            continue
        if "chapters" not in data:
            errors.append(f"{name}: missing top-level 'chapters'")
            continue
        data.setdefault("part", name.replace("part-", "").replace(".json", ""))
        parts.append(data)
    return parts, catalogs, errors


def validate(parts: list[dict]) -> list[str]:
    problems: list[str] = []
    for part in parts:
        pid = part.get("part", "?")
        for chapter in part.get("chapters", []):
            cid = chapter.get("chapter", "?")
            eps = chapter.get("endpoints")
            if not isinstance(eps, list) or not eps:
                problems.append(f"part-{pid} ch{cid}: no endpoints")
                continue
            for ep in eps:
                tag = f"part-{pid} ch{cid} {ep.get('endpoint', '<no endpoint>')}"
                if not ep.get("endpoint"):
                    problems.append(f"{tag}: missing endpoint")
                if not ep.get("purpose"):
                    problems.append(f"{tag}: missing purpose")
                if not ep.get("methods"):
                    problems.append(f"{tag}: missing methods")
                cat = ep.get("category")
                if cat not in VALID_CATEGORIES:
                    problems.append(f"{tag}: bad category {cat!r}")
                bad_ops = set(ep.get("operations") or []) - VALID_OPERATIONS
                if bad_ops:
                    problems.append(f"{tag}: bad operations {sorted(bad_ops)}")
                if ep.get("methods_observed") is not None:
                    problems.append(f"{tag}: methods_observed should be null")
                if not isinstance(ep.get("key_fields", []), list):
                    problems.append(f"{tag}: key_fields is not a list")
    return problems


def merge(parts: list[dict]) -> dict:
    chapters: list[dict] = []
    for part in parts:
        chapters.extend(part.get("chapters", []))

    # index every endpoint; report cross-chapter duplicates
    seen: dict[str, list[str]] = collections.defaultdict(list)
    for chapter in chapters:
        for ep in chapter.get("endpoints", []):
            seen[ep.get("endpoint", "")].append(str(chapter.get("chapter")))

    duplicates = {k: v for k, v in seen.items() if len(v) > 1}
    all_eps = [ep for ch in chapters for ep in ch.get("endpoints", [])]

    return {
        "source": "MIDAS-API-main/docs/manual + docs/plugin",
        "note": "Generated by merge_registry.py. Field names copied verbatim from the "
                "MIDAS NX Open API manual. No live-API observations are included.",
        "counts": {
            "parts": len(parts),
            "chapters": len(chapters),
            "endpoints": len(all_eps),
            "unique_endpoints": len(seen),
            "by_category": dict(sorted(collections.Counter(
                ep.get("category") for ep in all_eps).items())),
            "by_method": dict(sorted(collections.Counter(
                m for ep in all_eps for m in (ep.get("methods") or [])).items())),
            "by_resource": dict(sorted(collections.Counter(
                ep.get("resource") for ep in all_eps).items(), key=lambda kv: -kv[1])),
        },
        "duplicate_endpoints": duplicates,
        "chapters": chapters,
    }


def write_markdown(registry: dict) -> None:
    counts = registry["counts"]
    lines = [
        "# MIDAS NX Open API — 端点总表",
        "",
        f"- 来源：`MIDAS-API-main/docs/manual`（{counts['chapters']} 章）+ `docs/plugin`",
        f"- 端点数：**{counts['unique_endpoints']}**（去重后）／{counts['endpoints']}（含跨章重复）",
        f"- 生成方式：`merge_registry.py`，由 `part-*.json` 合并",
        "",
        "> 本表字段名逐字取自 MIDAS 官方 JSON Manual，**不含实机观测结论**。",
        "",
        "## 分类统计",
        "",
        "| 维度 | 分布 |",
        "| --- | --- |",
    ]
    for key, label in (("by_category", "category"), ("by_method", "method"), ("by_resource", "resource")):
        dist = counts.get(key) or {}
        rendered = " · ".join(f"`{k}` {v}" for k, v in dist.items())
        lines.append(f"| {label} | {rendered} |")

    if registry["duplicate_endpoints"]:
        lines += ["", "## 跨章重复端点", "", "| 端点 | 出现章节 |", "| --- | --- |"]
        for ep, chs in sorted(registry["duplicate_endpoints"].items()):
            lines.append(f"| `{ep}` | {', '.join(chs)} |")

    lines += ["", "## 端点明细", ""]
    for chapter in registry["chapters"]:
        eps = chapter.get("endpoints", [])
        lines += [
            "",
            f"### {chapter.get('chapter')}. {chapter.get('title')} （{len(eps)} 个）",
            "",
            f"来源：`{chapter.get('source')}`",
            "",
            "| 端点 | 方法 | 资源 | 操作 | 说明 | 字段数 |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for ep in eps:
            purpose = (ep.get("purpose") or "").replace("|", "\\|").replace("\n", " ")
            if len(purpose) > 110:
                purpose = purpose[:107] + "…"
            lines.append(
                f"| `{ep.get('endpoint')}` "
                f"| {', '.join(ep.get('methods') or [])} "
                f"| `{ep.get('resource')}` "
                f"| {', '.join(ep.get('operations') or [])} "
                f"| {purpose} "
                f"| {len(ep.get('key_fields') or [])} |"
            )

    with open(OUT_MD, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def main() -> int:
    parts, catalogs, errors = load_parts()
    if not parts:
        print("no endpoint part-*.json found in", BASE)
        return 1

    problems = validate(parts)
    registry = merge(parts)

    with open(OUT_JSON, "w", encoding="utf-8") as fh:
        json.dump(registry, fh, ensure_ascii=False, indent=2)
    write_markdown(registry)

    counts = registry["counts"]
    print(f"parts merged        : {counts['parts']}")
    print(f"chapters            : {counts['chapters']}")
    print(f"endpoints (unique)  : {counts['unique_endpoints']}")
    print(f"by category         : {counts['by_category']}")
    print(f"by method           : {counts['by_method']}")
    print(f"duplicate endpoints : {len(registry['duplicate_endpoints'])}")
    for catalog in catalogs:
        counts = catalog.get("counts", {})
        print(
            f"plugin catalogue    : part-{catalog.get('part')} "
            f"listed={counts.get('listed')} documented={counts.get('documented')} "
            f"deprecated={counts.get('deprecated')} unwritten={counts.get('unwritten')}"
        )
    print(f"wrote               : {OUT_JSON}")
    print(f"wrote               : {OUT_MD}")

    if errors:
        print("\nLOAD ERRORS:")
        for item in errors:
            print("  -", item)
    if problems:
        print(f"\nVALIDATION PROBLEMS ({len(problems)}):")
        for item in problems[:60]:
            print("  -", item)
        if len(problems) > 60:
            print(f"  … and {len(problems) - 60} more")
    return 0 if not errors else 2


if __name__ == "__main__":
    sys.exit(main())
