"""MCP server — v1.2 §37 (endpoint) / V2.1 §6–§11 (the four tools).

Two transports, exactly as 总纲/v1.2 require:

* **stdio** for local agents (``python -m app.mcp.server --transport stdio``);
* **streamable HTTP at ``/mcp``** for network clients
  (``python -m app.mcp.server --transport http``).  v1.2 §37: 「REST 管理 API 与
  MCP Protocol Endpoint 必须分离」 — ``/api/v1/*`` is management, ``/mcp`` is MCP,
  and the two envelopes must never be mixed (总纲 §4.3.2).

Schema publication (总纲 §0.4 唯一真源)
--------------------------------------
``MCPServer`` derives each tool's published ``inputSchema`` from the handler's
signature.  A **flat** signature — which is what the MCP protocol surface needs —
produces enums (from ``Literal``) but emits **no** ``additionalProperties`` key at
all, i.e. it is permissive.  V2.1 §6.1 / 裁决 B-4 require
``additionalProperties: false`` at every layer, so the authoritative schema
generated by :mod:`app.mcp.capabilities` is installed on each tool before the
server is built.  One schema object therefore serves both jobs: what the client
sees, and what the dispatcher validates against (see
:func:`app.mcp.dispatcher.validate_arguments`).

The handlers keep their ``Literal`` enums as well.  They are not redundant: they
are the SDK-side first line (a bad enum value is refused by pydantic before any
of our code runs), and they keep the signature self-documenting.
"""

import argparse
import sys
from typing import Any, Awaitable, Callable, Final, Literal, Sequence

from mcp.server.mcpserver import MCPServer
from mcp.server.mcpserver.tools import Tool

from app.adapters.base import AdapterMetadata, MidasAdapter
from app.adapters.midas_gen.adapter import CAPABILITIES, MidasNxAdapter
from app.adapters.mock.adapter import MockAdapter
from app.adapters.registry import AdapterRegistry, get_registry
from app.core.midas_config import MidasConfig, MidasConfigError, load_midas_config
from app.mcp.capabilities import (
    TOOL_EXECUTE,
    TOOL_MODEL,
    TOOL_QUERY,
    TOOL_TASK,
    actions_for,
    resources_for,
    task_status_values,
    task_type_values,
)
from app.mcp.dispatcher import ToolDispatcher
from app.mcp.tools import execute as execute_tool
from app.mcp.tools import model as model_tool
from app.mcp.tools import query as query_tool
from app.mcp.tools import task as task_tool
from app.services.task_service import TaskService, get_task_service

__all__ = [
    "SERVER_NAME",
    "SCHEMA_VERSION",
    "DEFAULT_HTTP_HOST",
    "DEFAULT_HTTP_PORT",
    "MCP_HTTP_PATH",
    "INSTRUCTIONS",
    "build_tools",
    "build_server",
    "register_configured_adapters",
    "register_mock_adapter",
    "main",
]

SERVER_NAME: Final[str] = "structai-midas"
#: V2.1 §6.4 / §31.1: the tool-schema version published in ``$id`` and here.
SCHEMA_VERSION: Final[str] = "2.1"
DEFAULT_HTTP_HOST: Final[str] = "127.0.0.1"
DEFAULT_HTTP_PORT: Final[int] = 8765
#: v1.2 §37: the MCP endpoint lives at ``/mcp``, never under ``/api/v1``.
MCP_HTTP_PATH: Final[str] = "/mcp"

INSTRUCTIONS: Final[str] = (
    "StructAI MIDAS 工程能力。四个工具：\n"
    "  midas_query   只读查询（server / client / capabilities / model / node / "
    "element / material / section / load / boundary / group / analysis / result / "
    "project）\n"
    "  midas_model   模型 CRUD + validate；delete 只逐 id 执行 "
    "DELETE {endpoint}/{id}（带 Assign 体的 DELETE 会清空整张表）\n"
    "  midas_execute 连接 / 项目 / 导入导出 / 计算 / 分析；默认异步返回 task_id\n"
    "  midas_task    任务轮询与结果（MCP 没有 push，只能轮询）\n"
    "所有调用返回统一的 MCP 信封：success / request_id / tool / status / data / "
    "task_id / warnings / errors。\n"
    "写操作超时后**不会**自动重试（超时 ≠ 回滚）；请先用 midas_execute "
    "action=sync 读回模型状态。"
)


# ---------------------------------------------------------------------------
# SDK-side enums, generated from the capability table (V2.1 §6.1 / 总纲 §0.4)
# ---------------------------------------------------------------------------
_QUERY_TARGETS = Literal[tuple(resources_for(TOOL_QUERY))]
_QUERY_ACTIONS = Literal[tuple(actions_for(TOOL_QUERY))]

_MODEL_RESOURCES = Literal[tuple(resources_for(TOOL_MODEL))]
_MODEL_ACTIONS = Literal[tuple(actions_for(TOOL_MODEL))]

_EXECUTE_RESOURCES = Literal[tuple(resources_for(TOOL_EXECUTE))]
_EXECUTE_ACTIONS = Literal[tuple(actions_for(TOOL_EXECUTE))]

_TASK_ACTIONS = Literal[tuple(actions_for(TOOL_TASK))]
#: V2.1 §26.2 / 总纲 §4.2.1 — closed vocabularies, owned by app.core.constants.
_TASK_TYPES = Literal[tuple(task_type_values())]
_TASK_STATUSES = Literal[tuple(task_status_values())]


def _present(payload: dict[str, Any]) -> dict[str, Any]:
    """Drop ``None`` values before dispatching.

    The SDK hands the handler **every** declared parameter, filling omitted ones
    with their default (``None``).  Forwarding those Nones would put
    ``"page": null`` in front of the dispatcher's schema validation, where
    ``{"type": "integer", "minimum": 1}`` rightly rejects it.  Dropping them
    restores "the client sent only what it sent".
    """
    return {key: value for key, value in payload.items() if value is not None}


# ---------------------------------------------------------------------------
# handlers — one per tool, flat signature, capability-derived enums
# ---------------------------------------------------------------------------
def _make_query_handler(
    dispatcher: ToolDispatcher,
) -> Callable[..., Awaitable[dict[str, Any]]]:
    async def midas_query(
        target: _QUERY_TARGETS,
        action: _QUERY_ACTIONS,
        id: str | int | None = None,
        query: dict[str, Any] | None = None,
        fields: list[str] | None = None,
        page: int | None = None,
        page_size: int | None = None,
        client_id: int | None = None,
        adapter: str | None = None,
        include_metadata: bool | None = None,
    ) -> dict[str, Any]:
        return await dispatcher.dispatch(
            TOOL_QUERY,
            _present(
                {
                    "target": target,
                    "action": action,
                    "id": id,
                    "query": query,
                    "fields": fields,
                    "page": page,
                    "page_size": page_size,
                    "client_id": client_id,
                    "adapter": adapter,
                    "include_metadata": include_metadata,
                }
            ),
        )

    return midas_query


def _make_model_handler(
    dispatcher: ToolDispatcher,
) -> Callable[..., Awaitable[dict[str, Any]]]:
    async def midas_model(
        action: _MODEL_ACTIONS,
        resource: _MODEL_RESOURCES,
        id: str | int | None = None,
        ids: list[str | int] | None = None,
        data: dict[str, Any] | list[Any] | None = None,
        options: dict[str, Any] | None = None,
        client_id: int | None = None,
        adapter: str | None = None,
    ) -> dict[str, Any]:
        return await dispatcher.dispatch(
            TOOL_MODEL,
            _present(
                {
                    "action": action,
                    "resource": resource,
                    "id": id,
                    "ids": ids,
                    "data": data,
                    "options": options,
                    "client_id": client_id,
                    "adapter": adapter,
                }
            ),
        )

    return midas_model


def _make_execute_handler(
    dispatcher: ToolDispatcher,
) -> Callable[..., Awaitable[dict[str, Any]]]:
    async def midas_execute(
        action: _EXECUTE_ACTIONS,
        resource: _EXECUTE_RESOURCES | None = None,
        data: dict[str, Any] | None = None,
        options: dict[str, Any] | None = None,
        client_id: int | None = None,
        adapter: str | None = None,
    ) -> dict[str, Any]:
        return await dispatcher.dispatch(
            TOOL_EXECUTE,
            _present(
                {
                    "action": action,
                    "resource": resource,
                    "data": data,
                    "options": options,
                    "client_id": client_id,
                    "adapter": adapter,
                }
            ),
        )

    return midas_execute


def _make_task_handler(
    dispatcher: ToolDispatcher,
) -> Callable[..., Awaitable[dict[str, Any]]]:
    async def midas_task(
        action: _TASK_ACTIONS,
        task_id: str | None = None,
        type: _TASK_TYPES | None = None,
        status: _TASK_STATUSES | None = None,
        since: str | None = None,
        page: int | None = None,
        page_size: int | None = None,
        include_result: bool | None = None,
        include_events: bool | None = None,
    ) -> dict[str, Any]:
        return await dispatcher.dispatch(
            TOOL_TASK,
            _present(
                {
                    "action": action,
                    "task_id": task_id,
                    "type": type,
                    "status": status,
                    "since": since,
                    "page": page,
                    "page_size": page_size,
                    "include_result": include_result,
                    "include_events": include_events,
                }
            ),
        )

    return midas_task


#: ``(tool module, handler factory)`` in v1.2 §37 declaration order.
_TOOL_SPECS: Final[tuple[tuple[Any, Callable[[ToolDispatcher], Callable[..., Any]]], ...]] = (
    (query_tool, _make_query_handler),
    (model_tool, _make_model_handler),
    (execute_tool, _make_execute_handler),
    (task_tool, _make_task_handler),
)


def _publish_authoritative_schema(tool: Tool, schema: dict[str, Any]) -> None:
    """Install the schema generated from the capability table.

    See the module docstring: the SDK-derived schema omits
    ``additionalProperties``, which V2.1 §6.1 / 裁决 B-4 forbid.  The installed
    object is the *same* schema the dispatcher validates against, so the client
    contract and the server check cannot disagree (总纲 §0.4).
    """
    tool.parameters = dict(schema)


def build_tools(dispatcher: ToolDispatcher) -> list[Tool]:
    """Build the four tools, each with its authoritative published schema."""
    tools: list[Tool] = []
    for module, factory in _TOOL_SPECS:
        handler = factory(dispatcher)
        tool = Tool.from_function(
            handler,
            name=module.TOOL_NAME,
            description=module.DESCRIPTION,
            # Unstructured output: the envelope is returned as JSON text, which is
            # what every MCP client reads.  Publishing an outputSchema for a
            # hand-shaped envelope would add a second contract to keep in sync.
            structured_output=False,
        )
        _publish_authoritative_schema(tool, module.SCHEMA)
        tools.append(tool)
    return tools


def build_server(
    *,
    name: str = SERVER_NAME,
    version: str = SCHEMA_VERSION,
    registry: AdapterRegistry | None = None,
    dispatcher: ToolDispatcher | None = None,
    task_service: TaskService | None = None,
    authorizer: Any = None,
) -> MCPServer:
    """Build the MCP server exposing exactly the four V2.1 tools.

    The registry is **not** populated here: registration is the Service layer's
    job (V2.1 §21 + §15 落库映射).  Use :func:`register_configured_adapters` (or
    :func:`register_mock_adapter`) first, or pass a pre-populated ``registry``.
    """
    resolved_registry = registry if registry is not None else get_registry()
    resolved_tasks = task_service if task_service is not None else get_task_service()
    resolved_dispatcher = dispatcher or ToolDispatcher(
        registry=resolved_registry,
        task_service=resolved_tasks,
        authorizer=authorizer,
    )
    return MCPServer(
        name=name,
        title="StructAI MIDAS MCP Server",
        description=(
            "StructAI 平台的 MIDAS 工程能力 MCP 服务：midas_query / midas_model / "
            "midas_execute / midas_task（V2.1 §7–§10）。"
        ),
        instructions=INSTRUCTIONS,
        version=version,
        tools=build_tools(resolved_dispatcher),
    )


# ---------------------------------------------------------------------------
# adapter registration (V2.1 §15 / §21)
# ---------------------------------------------------------------------------
def _metadata_for(adapter: MidasAdapter, *, version_range: str = ">=2024") -> AdapterMetadata:
    """§15 metadata without awaiting ``adapter.metadata()``.

    ``register()`` is synchronous and ``metadata()`` is a coroutine (V2.1 §13 vs
    §21 — see ``AdapterRegistry``'s docstring), so the metadata is assembled here
    from the three §13 properties.  It is identical to what the async
    ``metadata()`` returns for both shipped adapters.
    """
    return AdapterMetadata(
        code=adapter.code,
        name=f"{adapter.software} Adapter",
        software=adapter.software,
        version_range=version_range,
        protocol="http" if isinstance(adapter, MidasNxAdapter) else "memory",
        supports_query=True,
        supports_model=True,
        supports_execute=True,
        # 对接规范 §2.5.1: MIDAS has no async task API — the platform's Task
        # Engine provides it (V2.1 §26).
        supports_async_task=True,
        capabilities=[capability.code for capability in CAPABILITIES],
    )


def register_configured_adapters(
    registry: AdapterRegistry,
    config: MidasConfig | None = None,
) -> list[str]:
    """Register one adapter per enabled entry of ``config/midas.json``.

    Returns the registered adapter codes.  Raises
    :class:`~app.core.midas_config.MidasConfigError` when the config file is
    missing or malformed — the caller decides whether that is fatal.
    """
    resolved = config if config is not None else load_midas_config()
    codes: list[str] = []
    for connection in resolved.enabled:
        adapter = MidasNxAdapter(connection)
        registry.register(adapter, metadata=_metadata_for(adapter), replace=True)
        codes.append(adapter.code)
    return codes


def register_mock_adapter(
    registry: AdapterRegistry, *, code: str = "midas_gen"
) -> str:
    """Register the in-memory adapter (V2.1 §22) under a real adapter code.

    Only for local development and tests: the mock answers fabricated data, so it
    is never registered implicitly (``main()`` requires ``--allow-mock``).
    """
    adapter = MockAdapter(code=code, software="MIDAS Gen")
    registry.register(
        adapter, metadata=_metadata_for(adapter, version_range=">=2024"), replace=True
    )
    return adapter.code


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main(argv: Sequence[str] | None = None) -> int:
    """``python -m app.mcp.server --transport stdio|http``."""
    parser = argparse.ArgumentParser(
        prog="python -m app.mcp.server",
        description="StructAI MIDAS MCP server (V2.1 §7–§10).",
    )
    parser.add_argument(
        "--transport",
        choices=("stdio", "http"),
        default="stdio",
        help="stdio for local agents; http serves streamable HTTP at --path (default /mcp).",
    )
    parser.add_argument("--host", default=DEFAULT_HTTP_HOST)
    parser.add_argument("--port", type=int, default=DEFAULT_HTTP_PORT)
    parser.add_argument(
        "--path",
        default=MCP_HTTP_PATH,
        help="streamable HTTP path; v1.2 §37 keeps it separate from /api/v1.",
    )
    parser.add_argument(
        "--allow-mock",
        action="store_true",
        help=(
            "register the in-memory mock adapter when no MIDAS config is available "
            "(development only — it answers fabricated data)."
        ),
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    registry = get_registry()
    try:
        codes = register_configured_adapters(registry)
    except MidasConfigError as exc:
        codes = []
        print(f"[structai-mcp] {exc}", file=sys.stderr)

    if not codes:
        if not args.allow_mock:
            print(
                "[structai-mcp] 没有可用的 MIDAS adapter。请先配置 "
                "backend/config/midas.json（模板见 config/midas.example.json），"
                "或显式传 --allow-mock 使用内存 Mock（会返回伪造数据）。",
                file=sys.stderr,
            )
            return 2
        codes = [register_mock_adapter(registry)]
        print(
            f"[structai-mcp] --allow-mock：已注册内存 Mock adapter {codes[0]!r}；"
            "所有应答都是伪造的。",
            file=sys.stderr,
        )

    server = build_server(registry=registry)
    if args.transport == "stdio":
        server.run(transport="stdio")
    else:
        print(
            f"[structai-mcp] streamable HTTP on http://{args.host}:{args.port}{args.path}",
            file=sys.stderr,
        )
        server.run(
            transport="streamable-http",
            host=args.host,
            port=args.port,
            streamable_http_path=args.path,
        )
    return 0


if __name__ == "__main__":  # pragma: no cover - process entry point
    raise SystemExit(main())
