"""Render ROADMAP.md from the endpoint inventory and the live-evidence ledger.

Two files, because they answer different questions: docs/coverage.json says
what this SDK implements (status, module, chapter), and
contracts/verification/ledger.yaml says what a live session proved about it.
Until 2026-09-21 the second lived inside the first as a `live_verified` block
and also, separately, in the contract verification records - two ledgers that
drifted apart and disagreed about what `level` meant.

Run after editing either one.
"""
from __future__ import annotations

import json
import sys
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))

from verification_ledger import claims, load_records  # noqa: E402


def main() -> None:
    data = json.loads((ROOT / "docs" / "coverage.json").read_text(encoding="utf-8"))
    endpoints = data["endpoints"]

    # The ledger is keyed by endpoint; an entry without a claim has no live
    # evidence at all, which is a state the counts below already handle.
    ledger = claims()
    evidence = {
        e["endpoint"]: ledger.get(e["endpoint"]) for e in endpoints
    }

    by_chapter: "OrderedDict[str, list[dict]]" = OrderedDict()
    for e in sorted(endpoints, key=lambda e: e["chapter_file"]):
        by_chapter.setdefault(e["chapter_file"], []).append(e)

    total = len(endpoints)
    implemented = sum(1 for e in endpoints if e["status"] == "implemented")
    live_verified = sum(1 for e in endpoints if evidence[e["endpoint"]])

    # Read vs write, because one number for both overstates what is known:
    # a GET that answers proves the route exists and the response parses; only
    # a create/update/delete proves the SDK's *request* shape is one the server
    # accepts. "write" here means data (or a file on the NX host) was actually
    # mutated -- a POST that was refused before doing anything counts as read.
    write_verified = sum(
        1 for e in endpoints
        if evidence[e["endpoint"]] and evidence[e["endpoint"]].level == "write"
    )
    read_verified = sum(
        1 for e in endpoints
        if evidence[e["endpoint"]] and evidence[e["endpoint"]].level == "read"
    )
    unleveled = live_verified - write_verified - read_verified

    # Per-product, counted off the same resolved claims.
    by_product = {
        p: sum(
            1
            for e in endpoints
            if evidence[e["endpoint"]] and p in evidence[e["endpoint"]].products
        )
        for p in ("gen", "civil")
    }

    # D4 version matrix: every distinct (date, Gen build, Civil build) combo
    # the ledger cites. Read from the records rather than the resolved claims,
    # because a session an endpoint no longer cites as its establishing one
    # still happened - three /DESIGN/*/TABLE rows share a URL and were swept
    # on different builds, and resolving to one claim would drop a row here.
    sessions = sorted({
        (
            str(record["date"]),
            (record.get("nxVersions") or {}).get("gen", "?"),
            (record.get("nxVersions") or {}).get("civil", "?"),
        )
        for record in load_records()
        if record.get("nxVersions")
    })

    lines = [
        "# Roadmap",
        "",
        f"Generated by `scripts/gen_roadmap.py` from `docs/coverage.json` "
        f"(vendored from {data['vendored_from']}).",
        "",
        f"**{implemented}/{total} documented endpoints implemented.**",
        "",
        "## Verification status",
        "",
        "| Measure | Count | What it means |",
        "|---|---|---|",
        f"| Implemented | {implemented}/{total} | wrapped, typed, and unit-tested against a mocked server |",
        f"| Live-verified (any) | {live_verified}/{implemented} | exercised against a real Gen NX / Civil NX session |",
        f"| — live **write** | {write_verified}/{implemented} | actually created/updated/deleted data, or wrote a file on the NX host |",
        f"| — live **read** | {read_verified}/{implemented} | reads only: the route answers and the response parses |",
        f"| Not live-verified | {implemented - live_verified}/{implemented} | no live evidence recorded either way |",
        f"| Verified on Gen NX | {by_product['gen']}/{implemented} | |",
        f"| Verified on Civil NX | {by_product['civil']}/{implemented} | |",
        "",
        "**Read and write are counted separately on purpose.** A GET that "
        "answers proves the route exists and the response parses; only a "
        "create/update/delete round trip proves the *request* shape this SDK "
        "sends is one the server accepts. Most of the defects found so far — "
        "wrong field names, wrong enum values, wrong documented defaults — were "
        "invisible to reads. A row counted as read is not a weaker claim about "
        "the same thing; it is a claim about a different thing.",
        "",
        "Live-verification evidence lives in "
        "`contracts/verification/ledger.yaml` (product, build, date, and what "
        "was actually done), with the narrative in "
        "`docs/live_verification_notes.md`. Write coverage comes from "
        "`scripts/live_crud_check.py`; read coverage mostly from "
        "`scripts/live_readonly_sweep.py`.",
        "",
    ]

    if unleveled:
        lines += [
            f"> ⚠️ {unleveled} live-verified endpoint(s) have no `level` recorded "
            "and are counted in neither the read nor the write row. Set "
            '`level` to `"read"` or `"write"` on those ledger records.',
            "",
        ]

    if sessions:
        lines += [
            "Each row is one `(date, Gen build, Civil build)` combination the "
            "ledger cites, **not** one testing session. An entry's `date` is "
            "when it reached its current level and its builds are from the most "
            "recent check, so a row can pair an older date with a newer build.",
            "",
        ]
        lines.append("| Date | Gen NX build | Civil NX build |")
        lines.append("|---|---|---|")
        for date, gen_build, civil_build in sessions:
            lines.append(f"| {date} | {gen_build} | {civil_build} |")
        lines.append("")

    lines += [
        "> " + data["source_note"],
        "",
        "In the per-chapter tables below, the **Live** column is `W` for an "
        "endpoint with live write verification, `R` for live reads only, and "
        "blank for none.",
        "",
        "Pick any unchecked row, implement it in the listed `module`, add a test "
        "mirroring the pattern in `tests/db/test_node_element.py` (or "
        "`tests/test_doc.py` for `/doc/`, `/ope/`, `/view/`-style plain-function "
        "endpoints), then mark it `\"implemented\"` in `docs/coverage.json` and "
        "re-run this script.",
        "",
    ]

    for chapter_file, rows in by_chapter.items():
        done = sum(1 for r in rows if r["status"] == "implemented")
        lines.append(f"## {chapter_file} ({done}/{len(rows)})")
        lines.append("")
        lines.append("| | Live | Endpoint | Name | Products | Module |")
        lines.append("|---|---|---|---|---|---|")
        for r in rows:
            checkbox = "[x]" if r["status"] == "implemented" else "[ ]"
            claim = evidence[r["endpoint"]]
            # W beats R: a write round trip subsumes reading the record back.
            live = {"write": "W", "read": "R"}.get(
                claim.level if claim else None, "✅" if claim else "")
            products = "/".join(r["products"])
            lines.append(f"| {checkbox} | {live} | `{r['endpoint']}` | {r['name']} | {products} | `{r['module']}` |")
        lines.append("")

    (ROOT / "ROADMAP.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote ROADMAP.md - {implemented}/{total} implemented.")


if __name__ == "__main__":
    main()
